services:
  auctionDB:
    image: 'mongo'
    volumes:
      - auction_data:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "5000:5000"
    depends_on:
      - auctionDB

volumes:
  auction_data:
